### ISSUE TITLE
In Git Bash no mktemp

### ISSUE THREAD

**Issue by albertosantini** [rupa/z#103]
In Git Bash (on Windows) there is not mktemp.

A quick and dirty workaround:

```
# tempfile="$(mktemp "$datafile.XXXXXX")" || return
tempfile="/tmp/.z.tmp"
```

Maybe an awk approach or a _Z_DATA and _Z_DATA_OLD one may be feasible.

**Comment by abeldantas** [comment]
I'm using version 1.9.5 and it has this problem
git-ftp: line 28: mktemp: command not found

and in git-ftp line 28 I have:
readonly TMP_DIR="$(mktemp -d -t git-ftp-XXXX)"
