### ISSUE TITLE
z appears to not recognize a dot as a literal dot

### ISSUE THREAD

**Issue by chdiza** [rupa/z#113]
On MacOSX 10.8.4, with bash, I have the following folders: ~/.vim and /sourcecode/vim.    I've cd'd to both multiple times, but I go to the latter more.

I type `z .v` thinking that z will cd me to ~/.vim, but it takes me to /sourcecode/vim.   Huh?  The latter has no dot!  My best guess is that z isn't treating the `.` in `.vim` as a dot, but as a special regex char that makes `.v` match the more highly-weighted `/sourcecode/vim`.

I'd love for `z .v` to take me to ~/.vim.  I don't want to escape the dot to do that, since I might as well just type `cd .v*` if I have to reach for the backslash key and do `z \.v`.  (And BTW, escaping the dot with a backslash doesn't work anyway).

**Comment by roachsinai** [comment]
So each metacharacter like `+` also not recognize as a literal `+`, right?
