### ISSUE TITLE
Access a directory up to the latest matching regex

### ISSUE THREAD

**Issue by Alexis-D** [rupa/z#127]
Hey,

Is there a way to access the the 'root-most' directory that matches a regex? It's probably going to be clearer with an example, here are two paths I often access:

```
/path/to/3.12
/path/to/3.12/some/more/dir/bin/unix
```

So when I want to go to the 1st one I type `z 3.12` but as I access the 2nd one more often it usually jumps to this one instead (I access the second one by typing `z bin unix` fwiw). 

Is there a flag that would allow me to jump to the first dir? Has this idea been discussed already? Something like `z -u 3.12` would be great (`-u` standing for upper); it would take the directory returned by `z 3.12` but would use `dirname` on it, try to match the regex, repeat until the dir doesn't match anymore. And jump to the latest matching directory (I hope it makes sense).

Thanks!

**Comment by rupa** [comment]
argument order matters now, it's nice, gonna close this.
