### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by davegomez** [rupa/z#134]
I'm trying to use **z** with my **MacBook** but I'm getting this message everytime I try to reload the .bash_profile with source.

    -bash: /usr/local/etc/profile.d/z.sh: Permission denied

I got the message everytime, even when I try to install **z** from **Homebrew**.

How can I fix this?

**Comment by jasonkuhrt** [comment]
FWIW I did the same thing (missed the dot) ha.

**Comment by skywinder** [comment]
btw, sorry for what the meaning of `.` in that string?

**Comment by shmup** [comment]
@skywinder you need to `source` the script (which runs the script in the current shell session), and while you could:

`source /foo/bar/z.sh`

People say `.` because even though `source` is a synonym for dot/period '.' in bash,  it's not in POSIX sh, so for maximum compatibility use the period.
