### ISSUE TITLE
z acts like in zsh when ran from tmux

### ISSUE THREAD

**Issue by jozsefDevs** [rupa/z#140]
If I run z from tmux it outputs

`-bash: (r)_z_precmd: syntax error in expression (error token is "_z_precmd")`

so it is totally behaving like it is in zsh. It gets true for the `if compctl >/dev/null 2>&1; then` clause however it should not do under bash.

I suggest to somehow check if tmux is installed because it looks like getting this check totally wrong.

If I keep just the else part of this last check however it works charmfully (even from tmux), great stuff, thanks!

**Comment by FranzSkuffka** [comment]
When I run z from tmux it's working fine, using zsh.

**Comment by jozsefDevs** [comment]
I've created this issue when I used Ubuntu (12.something). Someone probably has to check again because now I use Max OS X (Yosemite) and it's working well in tmux. I don't have access to an Ubuntu box now :(.

**Comment by FranzSkuffka** [comment]
Ubuntu 15.4 here.

**Comment by jozsefDevs** [comment]
Okay, then solved. Thank you.
