### ISSUE TITLE
not creating .z in archlinux

### ISSUE THREAD

**Issue by nickleefly** [rupa/z#149]
I have `PROMPT_COMMAND`
```
  __prompt () {
    echo -ne "\033[m";history -a
    echo ""
    if [ $SHLVL -gt 1 ]; then
      { local i=$SHLVL; while [ $i -gt 1 ]; do echo -n '.'; let i--; done; }
    fi
    local DIR=${PWD/$HOME/\~}
    local HOST=${HOSTNAME:-$(uname -n)}
    HOST=${HOST%.local}
    echo -ne "\033]0;$(__git_ps1 "%s - " 2>/dev/null)host $HOST : dir$DIR\007"
    echo -ne "$(__git_ps1 "\033[41;31m[\033[41;37m%s\033[41;31m]\033[0m" 2>/dev/null)"
    echo -ne "\033[40;37m$USER@\033[42;30m$HOST\033[0m:$DIR"
    if [ "$NAVE" != "" ]; then echo -ne " \033[44m\033[37m$NAVE\033[0m"
    else echo -ne " \033[32m$(node -v 2>/dev/null)\033[0m"
    fi
  }
  export PROMPT_COMMAND='__prompt'
```

Added the following to `.bashrc` file, and sourced bashrc
```
_Z_NO_PROMPT_COMMAND=1
. ~/z/z.sh
```

after cd around, its not creating .z file

**Comment by rupa** [comment]
`z` works, in part, by adding a command to `$PROMPT_COMMAND`. Setting `$_Z_PROMPT_NO_PROMPT_COMMAND` implies you want to manually maintain how that command is inserted into your existing `$PROMPT_COMMAND`.

You've told `z` not to mess with your existing `$PROMPT_COMMAND`, but you haven't added its functionality yourself, so it's not working.

**Comment by nickleefly** [comment]
Thanks, after adding ` [[ "$(type -t _z)" ]] && _z --add "$(pwd -P 2>/dev/null)" 2>/dev/null` from [#44/comment](https://github.com/rupa/z/issues/44#issuecomment-6748871) . 
It works like a charm.
