### ISSUE TITLE
Support Symlinked Datafile

### ISSUE THREAD

**Issue by joeyhoer** [rupa/z#154]
The way the datafile (default `~/.z`) is currently maintained, does not respect the datafile as a symlink. It will be overwritten and the link will be broken.

The datafile location can, of course, be changed by setting the `$_Z_DATA` global.

In my case, I'd like`z` to use the default datafile location, but I'd like that file to be a symlink to elsewhere.

**Comment by rupa** [comment]
let's see how it goes
