### ISSUE TITLE
List entries with tab delimiter

### ISSUE THREAD

**Issue by ngryman** [rupa/z#156]
Hey,

For some reason `z | cut -f2` doesn't work, I suppose this is because you use spaces to separate fields.
Would it be possible to use tab character instead?

Thanks!

**Comment by ngryman** [comment]
Note, this works: `z | tr -s ' ' | cut -d ' ' -f 2`.

**Comment by rupa** [comment]
Probably not going to do this, as you point out, there's plenty of way to get this done with simple tools. I'm a big awk fan, so `z | awk '{print $2}`.

I've been considering refactoring things a bit, to separate display logic from core. At that point, delimiter will likely be `|` (in the core function)

**Comment by ngryman** [comment]
Alright, just curious why not `tab`? Because you want to control columns width?
