### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gust1n** [rupa/z#160]
Hi!

I noticed that you haven't included a license for your project, can you please consider doing it so we know how it can be used (as an open source project I hope).

**Comment by johnfb** [comment]
I thought the first line of z.sh:
`# Copyright (c) 2009 rupa deadwyler under the WTFPL license`
was referring to http://www.wtfpl.net/ as the license?

**Comment by gust1n** [comment]
Good catch, I must have missed it only looking in the readme and looking for a LICENSE file. Thanks
