### ISSUE TITLE
Make use of pushd

### ISSUE THREAD

**Issue by jomo** [rupa/z#162]
It would be useful to go back to the previous directory.
That's exactly what `pushd` and `popd` are made for, but `z` doesn't use them.

If `z` would automatically use `pushd`, you could actually "jump around, jump up _and get down_" by e.g. `z -b` (which would just run `popd`).

### Example

```shell
# pwd
/home/johndoe
# z foo; pwd
/var/lib/foo
# z -b; pwd
/home/johndoe
```

**Comment by ruduran** [comment]
You can go back to the previous directory with 'cd -' (And with the same
number of keystrokes!! :P)
Is there a scenario where 'cd -' would not do what 'z -b' would?

**Comment by jomo** [comment]
`mind = blown`

Didn't know that! That's not documented in `help cd` of `fish` nor `bash`.
It's actually only documented at **3 different locations** in `man bash` (although it works in fish, too):

0.  

  > `OLDPWD` The previous working directory as set by the `cd` command.
0.  

  > An argument of `-` is converted to `$OLDPWD` before the directory change is attempted.
0.  
  
  > If the tilde-prefix is a `~-`, the value of the  shell variable `OLDPWD`, if it is set, is substituted

Thanks a lot!

----

PS: So when you use z with bash, you can also use `z ~-` :P

**Comment by jomo** [comment]
> Is there a scenario where 'cd -' would not do what 'z -b' would?

Yes, `pushd` has an (infinite?) *stack* of directories, whereas `OLDPWD` only stores the last pwd.

**Comment by ptzz** [comment]
+1 This would be nice to have

**Comment by dimitriye98** [comment]
I'd prefer it not to auto `pushd`. I tend to use `pushd` and `popd` for short diversions, e.g. moving from a source directory to a build directory, and having it automatically do it every time would be bothersome.

In fact, my `.zshrc` actually has:
```sh
pushz() {pushd `z -e $@`}
alias pz=pushz
```
so that I can do just that when I want to jump.

**Comment by rupa** [comment]
yeah - I don't want to make presumtions or take over pushd. as noted, it's not too hard to wrap somethings if you want that functionality

**Comment by liloman** [comment]
I made it. ;)

https://github.com/liloman/dirStack
