### ISSUE TITLE
z without comments always show a list

### ISSUE THREAD

**Issue by Ninerian** [rupa/z#164]
z is showing me the list of all found directories when I call it without any arguments. Its like calling it with z -l.
Unfortunately, I don't know, what I changed to activate this behaviour.

System: OSX 10.11.1
Shell: Bash 4.3.42(1)

**Comment by rupa** [comment]
It's intended behavior and it's been that way for a long time. I suppose we could change it to take you to your overall most-frecent dir, not sure if I'd like that tho
