### ISSUE TITLE
Nothing being written to ~/.z

### ISSUE THREAD

**Issue by sangaline** [rupa/z#175]
I used z for about a week without issue and then it suddenly stopped updating the ~/.z file with new directories. I tried deleting it and it isn't being replaced. The z.sh is definitely being sourced. I'm using bash 4.3.042.

Any ideas why it might've stopped working? I'm happy to try anything out for debugging but I'm not sure where to start.

**Comment by sangaline** [comment]
I had made a modification to my PROMPT_COMMAND environment variable which was overwriting the '_z -add' command. All sorted now.

**Comment by paxperscientiam** [comment]
@sangaline thank you, this was exactly my problem!

**Comment by itwars** [comment]
PROMPT_COMMAND="myfunction;$PROMPT_COMMAND"
