### ISSUE TITLE
.z stops updating when the last directory in ~/.z does not exist

### ISSUE THREAD

**Issue by paulp** [rupa/z#177]
At least it does under bash. And the reason is [this logic](https://github.com/rupa/z/blob/master/z.sh#L52). The exit status of that command is not the return code from awk. It's the result of the last -d test. So if the last directory doesn't exist, it's 1.
```bash
% echo "/floop" > /tmp/test.txt
% while read f; do [ -d $f ] && echo $f; done </tmp/test.txt | awk ' { } ' ; echo $?
1
% echo "/" >> /tmp/test.txt
% while read f; do [ -d $f ] && echo $f; done </tmp/test.txt | awk ' { } ' ; echo $?
0
% echo "/floop" >> /tmp/test.txt
% while read f; do [ -d $f ] && echo $f; done </tmp/test.txt | awk ' { } ' ; echo $?
1
%
```
That return value is utilized [here](https://github.com/rupa/z/blob/master/z.sh#L78) where it silently bails out and deletes what would have been the updated .z file.

Since it never updates the list, it never purges the non-existent directory and is frozen on its current directory set until the file is repaired or removed.

This has been plaguing me for literally years and it's pretty satisfying to track it down. I don't know how it isn't seen more frequently. I wish you wouldn't silently exit on error conditions though.

**Comment by paulp** [comment]
See also the PIPESTATUS array.
```
% while read f; do [ -d $f ] && echo $f; done </tmp/test.txt | awk '{}'; echo "${PIPESTATUS[@]}"
0 0
% echo /floop >> /tmp/test.txt
% while read f; do [ -d $f ] && echo $f; done </tmp/test.txt | awk '{}'; echo "${PIPESTATUS[@]}"
1 0
```

**Comment by xHN35RQ** [comment]
Interesting. What might be a good solution for this?

**Comment by paulp** [comment]
There are a lot of ways to go but I sent a PR with the smallest change which came to mind. https://github.com/rupa/z/pull/178

**Comment by rupa** [comment]
Interesting and appreciated.

Issues:

* In zsh, the array is named `$pipestatus` (lowercase) so this solution doesn't work in both shells as currently written. I'm playing around with using `${PIPESTATUS[-1]}${pipestatus[-1]}`, which seems to work, but feels kind of gross :)
* There's another test of `$?` that seems to have the same issue. without such an irritating affect, I guess.

**Comment by rupa** [comment]
I've pushed a `pipestatus` branch, for comment and review.

**Comment by paulp** [comment]
Noting for posterity that I commented on c474e41 and propose an alternative in 98f6a8079d, pushed to #178.
