### ISSUE TITLE
[feature request] echo the current working directory

### ISSUE THREAD

**Issue by zhoufeng1989** [rupa/z#180]
Some directories have the same name, such as **src**, **lib**. Sometimes it is fussy to figure out which directory in. 
After z command, it would be a nicer if it can echo the current working directory.

**Comment by Rowno** [comment]
Most terminal prompts already output the current working directory after each command execution. But you could use the `pwd` command to output the current working directory: `z src && pwd`.

**Comment by zhoufeng1989** [comment]
I add a function in .zshrc:
`zz () {
	_z $* 2>&1 && pwd
}`

**Comment by rupa** [comment]
yeah, it's pretty trivial to do this with a wrapper or alias, and I begrudge options and configuration so I prefer solutions like yours. However, this approach does add an extra count to the dir you are in, so it's possible to argue I should add a configuration. In practice I can't imagine it matters though, and I prefer to leave things this way.

a bit surprised if zsh doesn't have a configuration to make cd verbose this way ...

**Comment by Rowno** [comment]
Check out https://github.com/sindresorhus/pure for an awesome zsh prompt.
