### ISSUE TITLE
options not work due to unrecognized modifier `1'

### ISSUE THREAD

**Issue by wallacexinyu** [rupa/z#185]
z xx works but z -option, say z -r xx does not work.

> _z:77: unrecognized modifier `1'

zsh:
zsh 5.0.7 (x86_64-unknown-linux-gnu)
OS:
Red Hat Enterprise Linux Server release 5.3

It seems that this version os zsh cannot understand the syntax. However I cannot change the version of zsh for some reason.

**Comment by rupa** [comment]
not sure what's going on with zsh there. It's substring extraction, works for me with 5.0.8 - i see some comments about zsh having another syntax for substrings, not sure what the story is. Not inclined to add a bunch of conditional logic to fix this without a fuller understanding. you might be able to set some compatibility option in zsh to get things working ...

**Comment by wallacexinyu** [comment]
Sorry for late response. I think it might be caused by specific versions of zsh. I changed the version to 5.0.8 and it works now.
Thanks!
