### ISSUE TITLE
Jump too simple

### ISSUE THREAD

**Issue by fishioon** [rupa/z#187]
use "z -v", show:
""""
24         /usr/bin
50         /Users/fish/git
56         /Users/fish/work/src/Qingyi/admin
90         /Users/fish/work/src/Qingyi/is
232        /Users/fish/Github/wxgo
""""
when use "z is", I want jump to "/Users/fish/work/src/Qingyi/is" dir, but jump to "/Users/fish/Github/wxgo".
I think just "fish" contain "is".

**Comment by brandonsturgeon** [comment]
Cd into `/Users/fish/work/src/Qingyi/is` directly more often.
