### ISSUE TITLE
Suggestion: Z is awesome. It would be great to have a similar command for history.

### ISSUE THREAD

**Issue by farseenabdulsalam** [rupa/z#188]
Z is a real productivity booster.
It would be great to have a similar command h for history.
For example, I frequently tweak various config files here and there, especially i3wm's configs.
If there existed a similar command, I could type: `h vim i3 <tab>` to have this autocompleted to `h vim ~/.i3/config`. Pressing enter would run the command after h.
I would like to contribute to this, but don't know where to start.

**Comment by johnfb** [comment]
if your using bash, the default is ctrl+r to search history. Though it
shows the most recent that matches and then lets you scroll through them
rather than the most frequent/recent one.

**Comment by rupa** [comment]
I don't have a need for this, because, in addition to what @johnfb said, I have this in my ~/.inputrc

    $if mode=emacs
        # "\e[A" and "\e[B" being whatever your terminal uses for up & down.
        "\e[A": history-search-backward
        "\e[B": history-search-forward
        # (bonus) Two escapes clear command line.
        "\e\e": "\C-a\C-k"
    $endif

which makes up and down do history-search like `^R`, and is Good Enough For Me.

**Comment by doubleloop** [comment]
If you are using zsh, I recommend https://github.com/psprint/zsh-navigation-tools for history

**Comment by balta2ar** [comment]
You might want to look as https://github.com/junegunn/fzf, which integrates with Ctrl-R to allow you fuzzy search through your history. Really awesome, can't live without it.

**Comment by liloman** [comment]
Hi,

It's amazing how you can spend 2 minutes reading other people troubles and found out that we all have the same kind of unresolved problems. :)

I will start tomorrow in this issue and when it'll be done I'll post it here.

I already have the framework to make easily the [bash<->readline communication](https://github.com/liloman/dotfiles/blob/bc1c5b1050a95f24b0f82d2a34622da73276a5bb/bash/.inputrc#L524) . I want now dynamic on shell completions (I already made the [static shell completions](https://github.com/liloman/generate-autocompletion) also ;)).

The closer of  what @farseenabdulsalam means is [dynamic-complete-history](https://github.com/liloman/dotfiles/blob/bc1c5b1050a95f24b0f82d2a34622da73276a5bb/bash/.inputrc#L484) but with substring and that it's what I'm going to implement very soon with completions (if it's even possible and nice of course). :trophy:

**Comment by liloman** [comment]
[Done!](https://github.com/liloman/dotfiles/blob/e509f95bbd1359cddba06dd839e0c0f01e1c0c25/bash/.inputrc#L547) :dancer: 

It was pretty easy I don't think I will try to implement on-fly dynamic autocompletions "soon" cause I don't have much time and I'm more than happy with this.
I have bind them to the default shitty C-r/C-s that never used (can't understand why people insist on using them ¿?).

```bash
>vi ~/.bashrc
>cp ~/.bashrc /tmp/bashrc1
>...
>mv rc (C-r)
Enter Control-q to reset search
>mv /tmp/bashrc1(C-r)
>mv ~/.bashrc(C-s)
>mv /tmp/bashrc1 /tmp/win
```

No C, no ncurses, no python just Bash. :)

**Comment by liloman** [comment]
Sorry for the spam but I wanted to let you know that I have made a library/framework for this stuff with everything explained.

[asyncBash](https://github.com/liloman/asyncBash)

Cheers

**Comment by rupa** [comment]
interesting discussion but out of scope for this project so ima close this
