### ISSUE TITLE
Fails under zsh

### ISSUE THREAD

**Issue by Majora320** [rupa/z#192]
When using zsh, z fails with the line: "bad math expression: operator expected at \`precmd_fun...'"
To fix this, just add `#!/usr/bin/env bash` to the top of the z.sh script.

**Comment by Rowno** [comment]
Works fine for me under zsh.

**Comment by Majora320** [comment]
That may be, but my zsh setup may be different than yours, and if the line `#!/usr/bin/env bash` was added it would fix my problem.

**Comment by rupa** [comment]
Adding a shebang isn't going to help, as we're sourcing, not executing, this code.

It might help if you want to figure out what the actual "bad math expression" in your "precmd_fun..." is.

**Comment by Majora320** [comment]
I found out what the problem was.
In my ~/.zshrc I sourced my ~/.bashrc under bash emulation mode, and my ~/.bashrc source the z script. It seems to be a bug with `emulate bash` mode. Fixed by removing the `emulate bash` before `source .bashrc`.
