### ISSUE TITLE
z doesn't record cd

### ISSUE THREAD

**Issue by antonmedv** [rupa/z#202]
I deleted ~/.z file but new file doesn't created and history of cd doesn't recorded. How to this it? Thanks.

**Comment by rupa** [comment]
* Are you using bash or zsh
* Are you sure you are sourcing and not executing z.sh

**Comment by antonmedv** [comment]
I'm using bash. 
I've installed it with brew and added to `~/.profile` – `. /usr/local/etc/profile.d/z.sh`

**Comment by antonmedv** [comment]
Please, help. I'm really want in back)
`z --add /somepath` working, `z s` also, but `cd` doesn't record where i'm going.

**Comment by rupa** [comment]
something is probably overwritting PROMPT_COMMAND or it's not getting added for some reason. you can look and see if the `z --add` stuff is there when you `echo $PROMPT_COMMAND`

**Comment by antonmedv** [comment]
Thanks a lot! That helped. Another program override prompt. Will be cool to add info about it to installation or troubleshooting doc's section.
