### ISSUE TITLE
Current stable release version?

### ISSUE THREAD

**Issue by ilovezfs** [rupa/z#205]
Based on https://github.com/rupa/z/releases it's not clear to me whether 1.9 or 1.11 is the current stable release version. Could you clarify which should be in Homebrew now? Thanks!

**Comment by rupa** [comment]
probably still 1.9 - the async commits are a bit suspect, it seems.

**Comment by ilovezfs** [comment]
@rupa cool. Thanks!

**Comment by ilovezfs** [comment]
@rupa time for a new tag or do you wan't Homebrew still on 1.9?
