### ISSUE TITLE
prompt choice like in v

### ISSUE THREAD

**Issue by ww7** [rupa/z#228]

**Comment by maiermic** [comment]
I don't know the prompt choice of v. Is it similar to [n-z](https://github.com/maiermic/n-z)?

**Comment by rupa** [comment]
very intentionally do not have this behaviour. prefer ending up in the "wrong" place sometimes and needing to adjust the mnemonic to having an extra step all the time.

You should be able to wrap z -l to make it a list picker if you really want.
