### ISSUE TITLE
[with] Can I have an option to change compound score from 9000 to other ?

### ISSUE THREAD

**Issue by skywind3000** [rupa/z#231]
Cygwin is much slower than native linux, and I am using z.sh everyday to jump around on cygwin.
Default aging threshold 9000 is too high, It has more than 3000 paths collected in my .z data file.
And there is a noticeable delay every time when you press Enter.

Is it possible to have a `$_Z_MAX_SCORE` option to change the threshold ? if so, I don't need delete entries in my data file manually.

**Comment by rupa** [comment]
yeah this seems OK to me

**Comment by skywind3000** [comment]
thanks
