### ISSUE TITLE
how to support vim?

### ISSUE THREAD

**Issue by cizel** [rupa/z#240]
RT, how to support vim

**Comment by alphaCTzo7G** [comment]
What do you mean by support vim?

**Comment by alphaCTzo7G** [comment]
z is a command line utility.. If you want to us it inside vim, you can use it with vim's `argslist`, as far as I can see: http://vimcasts.org/episodes/meet-the-arglist/..

for example.. when I need to search in vim across specific types of files.. I typically use the following command: 

`noautocmd vim /Users.*\n*.*code/g `find /home/username \( -type f -regextype posix-extended -regex  '.*' \) -exec grep -lI '.*' {} \;``

Here `find /home/username \( -type f -regextype posix-extended -regex  '.*' \) -exec grep -lI '.*' {} \;`

is passed as a argslist to `vimgrep`, even thought `find` and `grep` are command line utilities.

You can probably do the same with `z` as well.

**Comment by cizel** [comment]
thanks~
