### ISSUE TITLE
Completion broken?

### ISSUE THREAD

**Issue by taschmidt** [rupa/z#252]
Sorry if this isn't a "z" problem.  I just started noticing that as soon as I type "z [space]", it changes to "_z 2>&1 ".  It never used to do that before and I have no idea what changed.  If I type a partial directory after that and hit enter, it'll still switch to that directory.  So that's good.  However, hitting TAB no longer gives me auto complete suggestions.  Anyone have any idea what's wrong?

**Comment by rupa** [comment]
you've got some "expand aliases" setting going

**Comment by taschmidt** [comment]
Doh!  You're right, now that you mention it, it started when I added the globalias plugin (https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/globalias).  Removing it fixes everything.
