### ISSUE TITLE
Cannot source /usr/share/z/z.sh

### ISSUE THREAD

**Issue by navdeepio** [rupa/z#257]
`bash:` /usr/share/z/z.sh: line 87: syntax error near unexpected token `elif'
bash: /usr/share/z/z.sh: line 87: `    elif [ "$1" = "--complete" -a -s "$datafile" ]; then'`

I've put this in my bashrc. Using archlinux!!

**Comment by rupa** [comment]
i suspect the file has bad line endings for whatever reason

**Comment by navdeepio** [comment]
Downloaded the raw file and tried to source it.. same result.

**Comment by navdeepio** [comment]
cleaned up my .bashrc using shellcheck.net.
Resolved the issue, closing this for now.
