### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by zachriggle** [rupa/z#273]
Currently there's no license for z, which might restrict its use in some business settings.  https://choosealicense.com has lots of information on different ones, I recommend MIT since it's very open.

**Comment by rupa** [comment]
there is no LICENSE file, but there is a license

**Comment by zachriggle** [comment]
WTFPL, got it.  Mind adding a LICENSE file for clarity?  I realize the irony in adding an explicit license for WTFPL, but it would still be useful.
