### ISSUE TITLE
z -h does not work

### ISSUE THREAD

**Issue by homogulosus** [rupa/z#287]
I installed the script as indicated and everything works for me except the -h argument.
I did a homebrew installation afterwards and I get the same problem. 

``` bash
$ z -h
z [-cehlrtx] args
$
```

That's all I get. Simlink is correctly created in the manuals folders. 
any idea?

**Comment by rediffusion** [comment]
Hello! 🙂

 How can I install it?

**Comment by homogulosus** [comment]
This issue is dead. I tried a python version of z, very happy with it and it is mantained ;)

**Comment by rediffusion** [comment]
@homogulosus

 Hey, bro, I find good alternative [zsh-z](https://github.com/agkozak/zsh-z) 
1️⃣ git clone https://github.com/agkozak/zsh-z $ZSH_CUSTOM/plugins/zsh-z
2️⃣ code ~/.zshrc 
3️⃣ In plugins section add this:
**zsh-z**

---

 This is easy, cheers! 👍

**Comment by rediffusion** [comment]
Hello again! 🙂
Bro, actually it's working!

Terminal > code ~/.zshrc > plugins > add just add **z** thats all.
After going to Terminal type **z**! That's all!

Cheers! 👍
