### ISSUE TITLE
When starting fresh, outside $HOME: _z:24: no such file or directory: /home/<user>/.z

### ISSUE THREAD

**Issue by rking** [rupa/z#92]
If I do like: `cd /tmp; RM ~/.z` I get invariable warnings like in the subject above.

I thought I'd have time to hit this one, but not tonight.

**Comment by goofansu** [comment]
+1

**Comment by LandonSchropp** [comment]
+1

**Comment by cmcnamara87** [comment]
+1

**Comment by ruduran** [comment]
This seems to be solved by now. I'm not able to reproduce it.

**Comment by ctaylo21** [comment]
Just happened to me on a fresh install of z via brew (in case anyone was wondering if this is still open)

`_z:22: no such file or directory: /Users/username/.z`

**Comment by sommerper** [comment]
Just installed via Brew and it also happened to me.
1. Added `. /usr/local/etc/profile.d/z.sh` to my `.zshrc`
2. Open new shell and cd to a dir.
3. _z:22: no such file or directory: /Users/username/.z
4. Open new shell.
5. z works.

**Comment by Nezteb** [comment]
Bump #256.
